name: ml_full_dev
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python and Environment Management
  - python=3.11.8

  # Data Science Libraries
  - numpy=1.26.4
  - pandas>=2.2.1
  - scipy>=1.12.0
  - scikit-learn>=1.4.1
  - statsmodels>=0.14.1
  - matplotlib>=3.8.3
  - seaborn>=0.13.2
  - jupyter>=1.0.0
  - jupyterlab>=4.1.5

  # Machine Learning Libraries
  - xgboost>=2.0.3
  - lightgbm>=4.3.0
  - catboost>=1.2.3
  - optuna>=3.6.1
  - shap>=0.45.0

  # Deep Learning Libraries
  - pytorch>=2.3.0  # Relaxed to allow solver flexibility
  - torchvision>=0.18.0
  - torchaudio>=2.3.0
  - keras>=3.0.5

  # Computer Vision Libraries
  - opencv>=4.9.0
  - pillow>=10.2.0
  - scikit-image>=0.22.0

  # Web Frontend Development
  - flask>=3.0.2
  - fastapi>=0.110.0
  - streamlit>=1.32.2
  - uvicorn>=0.29.0
  - pydantic>=2.6.4

  # Utilities
  - h5py>=3.10.0
  - tqdm>=4.66.2
  - requests>=2.31.0

  # Pip installations
  - pip
  - pip:
      - tensorflow-macos==2.16.1
      - tensorflow-metal==1.2.0  # Updated to latest available version
      - tensorflow-datasets>=4.9.4
      - torchmetrics>=1.3.1
      - albumentations>=1.4.2
      - pytorch-lightning>=2.2.1
